services:
  stat-server:
    build: stat/stat-server
    image: stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/stat
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat

  stat-db:
    image: postgres:16.1
    container_name: stat-postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=stat
    volumes:
      - C:/Users/Vladislav/IdeaProjects/java-explore-with-me/stat/stat-server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: main-server
    image: main-server
    container_name: main-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main
      - SPRING_DATASOURCE_USERNAME=main
      - SPRING_DATASOURCE_PASSWORD=main

  ewm-db:
    image: postgres:16.1
    container_name: main-postgres
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB=main
    volumes:
      - C:/Users/Vladislav/IdeaProjects/java-explore-with-me/main-server/src/main/resources/Schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10