DROP TABLE IF EXISTS endpoint_hit CASCADE;

CREATE TABLE IF NOT EXISTS endpoint_hit (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  app VARCHAR(200) NOT NULL,
  uri VARCHAR(200) NOT NULL,
  ip VARCHAR(15) NOT NULL,
  "timestamp" TIMESTAMP WITHOUT TIME ZONE NOT NULL
);